//Exception

void main(){
  List x = [10, 20, 30];

  try{print(x[0]);
  print(x[5]);
  } on RangeError{
    print("Error: ‡∏Å‡∏£‡∏∏‡∏ì‡∏≤‡∏≠‡∏¢‡πà‡∏≤‡∏õ‡πâ‡∏≠‡∏ô‡πÄ‡∏•‡∏Ç‡∏®‡∏π‡∏ô‡∏¢‡πå.......");
  }on FormatException{
    print("Error: ‡∏Å‡∏£‡∏∏‡∏ì‡∏≤‡∏õ‡πâ‡∏≠‡∏ô‡∏ï‡∏±‡∏ß‡∏≠‡∏±‡∏Å‡∏©‡∏£.......");
  }catch(err){
    print("Error: Please contract with IT support" + err.toString());
    
  }finally{
   //‡∏ó‡∏≥‡∏á‡∏≤‡∏ô‡∏ó‡∏∏‡∏Å‡∏Ñ‡∏£‡∏±‡πâ‡∏á‡πÑ‡∏°‡πà‡∏ß‡πà‡∏≤‡∏à‡∏∞‡πÄ‡∏Å‡∏¥‡∏î exception  ‡πÉ‡∏ô try ‡∏´‡∏£‡∏∑‡∏≠‡πÑ‡∏°‡πà
    print("Bye bye ü§´");

  }

}


